import Head from 'next/head'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div className="flex flex-col items-center">
      <Head>
        <title>Rotational Churner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="w-100 flex mt-28">
        <div className="w-3/12 fixed">
          <h3 className="text-lg font-medium">Navigation</h3>
          <ul className="font-medium text-gray-500">
            <li className="my-2"><a className="cursor-pointer hover:text-black" href="#about">About</a></li>
            <li className="my-2"><a className="cursor-pointer hover:text-black" href="#rotational_churner">Rotational Churner</a></li>
            <li className="my-2"><a className="cursor-pointer hover:text-black" href="#dataset">Dataset</a></li>
            <li className="my-2"><a className="cursor-pointer hover:text-black" href="#methods">Methods</a></li>
            <li className="my-2"><a className="cursor-pointer hover:text-black" href="#prototype">Prototype</a></li>
          </ul>
        </div>
        <div className="w-9/12 ml-64">

          <a className="relative -top-28" id="about"></a>
          <h1 className="font-bold text-5xl" id="about">About this Website</h1>
          <p className="my-5">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Atque dolores maxime temporibus quia vel aliquam sit odit quisquam maiores! Est!</p>
          <p className="my-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste illum aliquam debitis? Vero, ducimus possimus! Consectetur nesciunt amet ipsam a illum quod enim necessitatibus exercitationem.</p>

          <a className="relative -top-28" id="rotational_churner"></a>
          <h1 className="font-bold text-5xl mt-10">Rotational Churner</h1>
          <p className="my-5">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Atque dolores maxime temporibus quia vel aliquam sit odit quisquam maiores! Est!</p>
          <p className="my-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste illum aliquam debitis? Vero, ducimus possimus! Consectetur nesciunt amet ipsam a illum quod enim necessitatibus exercitationem.</p>
          <p className="my-5">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Molestiae autem maxime, doloremque consequuntur incidunt tempora non nulla rerum esse nesciunt quibusdam nam odit recusandae dolorem labore minus hic dolore commodi obcaecati aliquid repellendus nobis quis aspernatur eos. Laboriosam fugit enim ullam porro maiores amet et quidem, ut sunt reiciendis dignissimos deleniti soluta necessitatibus quam. Quae ipsa vel labore provident quas, porro debitis dicta. Modi tempore distinctio ut, quidem nulla, exercitationem, eum sapiente libero repellendus incidunt aspernatur esse! Aliquam tempore animi incidunt velit a cumque! At fuga maxime laboriosam alias, id aut voluptatum iure sunt nisi eligendi nobis, ab fugit quae.</p>

          <a className="relative -top-28" id="dataset"></a>
          <h1 className="font-bold text-5xl mt-10">Dataset Used</h1>
          <p className="my-5">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Atque dolores maxime temporibus quia vel aliquam sit odit quisquam maiores! Est!</p>
          <p className="my-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste illum aliquam debitis? Vero, ducimus possimus! Consectetur nesciunt amet ipsam a illum quod enim necessitatibus exercitationem.</p>
          <p className="my-5">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Molestiae autem maxime, doloremque consequuntur incidunt tempora non nulla rerum esse nesciunt quibusdam nam odit recusandae dolorem labore minus hic dolore commodi obcaecati aliquid repellendus nobis quis aspernatur eos. Laboriosam fugit enim ullam porro maiores amet et quidem, ut sunt reiciendis dignissimos deleniti soluta necessitatibus quam. Quae ipsa vel labore provident quas, porro debitis dicta. Modi tempore distinctio ut, quidem nulla, exercitationem, eum sapiente libero repellendus incidunt aspernatur esse! Aliquam tempore animi incidunt velit a cumque! At fuga maxime laboriosam alias, id aut voluptatum iure sunt nisi eligendi nobis, ab fugit quae.</p>

          <a className="relative -top-28" id="methods"></a>
          <h1 className="font-bold text-5xl mt-10">Methods Applied</h1>
          <p className="my-5">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Atque dolores maxime temporibus quia vel aliquam sit odit quisquam maiores! Est!</p>
          <p className="my-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste illum aliquam debitis? Vero, ducimus possimus! Consectetur nesciunt amet ipsam a illum quod enim necessitatibus exercitationem.</p>
          <p className="my-5">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Molestiae autem maxime, doloremque consequuntur incidunt tempora non nulla rerum esse nesciunt quibusdam nam odit recusandae dolorem labore minus hic dolore commodi obcaecati aliquid repellendus nobis quis aspernatur eos. Laboriosam fugit enim ullam porro maiores amet et quidem, ut sunt reiciendis dignissimos deleniti soluta necessitatibus quam. Quae ipsa vel labore provident quas, porro debitis dicta. Modi tempore distinctio ut, quidem nulla, exercitationem, eum sapiente libero repellendus incidunt aspernatur esse! Aliquam tempore animi incidunt velit a cumque! At fuga maxime laboriosam alias, id aut voluptatum iure sunt nisi eligendi nobis, ab fugit quae.</p>

          <a className="relative -top-28" id="prototype"></a>
          <h1 className="font-bold text-5xl mt-10">Prototype</h1>

        </div>
      </div>
    </div>
  )
}
